

> Import Libraries




In [89]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import Data and Shuffle

In [90]:
data_set_merge=pd.read_csv("Merge_elements_data.csv")

ds =data_set_merge.sample(frac=1)
ds.head()

unique_ids      ids category_names  \
8317   bf4a6402-6c4f-41ba-9ea1-9ea61f85abf7-00112b9a  1125274          Walls   
15308  9fdaeaf0-413e-4713-b1a8-e36ef2350b07-0012a3e0  1221600      Furniture   
18686  8b3eabb2-c104-40eb-be65-6bf63195728c-000f86ac  1017516      Furniture   
230    953fa245-a320-4cd6-9f55-a8b06715b17d-0053656b  5465451          Walls   
6044   df882178-94ac-458b-b72a-1fcd46f2e288-005e6968  6187368          Doors   

                            family_names           type_names  \
8317                          Basic Wall              בטון 20   
15308                BO-Bathroom cabinet  BO-Bathroom cabinet   
18686  HermanMiller_Collection_SoloChair        No Upholstery   
230                           Basic Wall              בלוק 10   
6044            Wooden Door with opening        80/210 + צוהר   

                                            host_ids   BB_X_dims   BB_Y_dims  \
8317                                               -  242.056893  185.000000   
15308                                              -   80.000000   90.787294   
18686                                              -   48.450413   73.495073   
230                                                -  370.005204  289.500000   
6044   df882178-94ac-458b-b72a-1fcd46f2e288-005e6967   80.000000  210.000000   

       BB_Z_dims    BB_volumes                               BB_centers  \
8317   20.000000  8.956105e+05     {-16619.614638, 13001.790344, 552.5}   
15308  56.158406  4.078776e+05     {805.654883, 504.30126, 2985.513647}   
18686  55.391015  1.972400e+05  {3687.966005, -1042.388169, 336.545354}   
230    10.000000  1.070000e+06       {4952.578941, 4125.127519, 509.75}   
6044   81.500000  1.370000e+06       {-3104.958297, -84.015918, 1895.0}   

                   BB_plane_Zs  solid_volumes room_names  
8317                   {1,0,0}  895610.504700          -  
15308                  {1,0,0}   47899.207930          -  
18686  {-0.512784,-0.858518,0}    7776.191224          -  
230                   {-1,0,0}  903165.065600          -  
6044                  {-1,0,0}  100758.000000          -

Organize Dataset by Name


In [99]:
dataset=ds[["category_names","BB_X_dims","BB_Y_dims","BB_Z_dims","BB_volumes","solid_volumes"]]
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values
print(X)
# sampleArray=np.array(X)
# convertedArray = sampleArray.astype(np.float)


[[2.42056893e+02 1.85000000e+02 2.00000000e+01 8.95610505e+05
  8.95610505e+05]
 [8.00000000e+01 9.07872940e+01 5.61584060e+01 4.07877580e+05
  4.78992079e+04]
 [4.84504130e+01 7.34950730e+01 5.53910150e+01 1.97240016e+05
  7.77619122e+03]
 ...
 [3.00000000e-01 6.00000000e+01 1.15000000e+02 2.07000001e+03
  2.07000000e+03]
 [2.50000000e+02 5.00000000e+01 1.90000000e+02 2.38000000e+06
  8.42857861e+05]
 [8.46419890e+01 1.20000000e+02 2.00000000e+00 2.03140773e+04
  2.03140773e+04]]


Encoing the Independent Var

In [94]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

Encoding Dependent Var


In [100]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Splitting Dataset into training set and test set


In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [102]:
print(X_train)

[[1.88000000e+02 2.51000000e+02 2.98432150e+01 1.41000000e+06
  1.06096252e+05]
 [2.00000000e+02 1.21296026e+02 4.48475000e+01 1.09000000e+06
  4.00898328e+04]
 [5.60396070e+01 3.42500000e+02 2.50000000e+01 4.79839131e+05
  4.65221520e+05]
 ...
 [7.00000000e+01 2.10000000e+02 1.40000000e+01 2.05800000e+05
  9.51000000e+04]
 [9.00000000e+01 3.05000000e+02 1.00000000e+01 2.74500000e+05
  2.74500000e+05]
 [1.70000000e+01 4.95928704e+02 2.04996132e+02 1.73000000e+06
  1.73000000e+06]]


In [103]:
print(X_test)

[[3.04800000e+01 1.82880000e+02 1.21920000e+02 6.79604318e+05
  1.89322800e+05]
 [4.16000000e+00 2.59500000e+00 1.52000000e-01 1.64087000e+00
  1.64087000e+00]
 [1.00000000e+01 2.10000000e+02 1.34799787e+03 2.83000000e+06
  3.45599573e+05]
 ...
 [8.12800000e+01 9.00000000e+01 7.00000000e+01 5.12064000e+05
  2.70608641e+05]
 [7.00000000e+01 2.10000000e+02 7.40000000e+00 1.08780000e+05
  7.92600000e+04]
 [3.42268676e+02 2.80000000e+02 2.00000000e+01 1.92000000e+06
  1.92000000e+06]]


In [104]:
print(y_train)

[5 5 4 ... 0 4 1]


In [105]:
print(y_test)

[2 4 1 ... 2 0 4]


Feature Scalling


In [106]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Trainig the SVM Model on the training set


In [107]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

Confusion Matrix


In [109]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  19    0   19    1  433    0]
 [   3  233   34    5   12    0]
 [   0   25  296    0   32    0]
 [  14    3  241    2   27    0]
 [   3    1   10    0 1960    0]
 [   1    5  102    0  277    2]]


0.6680851063829787