

> Import Libraries




In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

Import Data and Shuffle

In [2]:
data_set_merge=pd.read_csv("dataset-02-clean.csv")

ds =data_set_merge.sample(frac=1)
ds.head()

unique_ids      ids category_names  \
897    02002ca4-2adf-4a5e-bf93-230816bb511b-005c5e91  6053521          Walls   
1267   e538c556-7242-485a-8e0e-bdc8fc5ca5c3-006a3793  6961043          Walls   
8598   6f694c75-579d-4918-bd7a-bee6268d8842-0017f948  1571144         Floors   
18027  818d733b-671f-43c4-bb01-f436f882d4b7-00057d2d   359725          Walls   
16722  3cd6a76e-baaa-4345-876e-def6261f4ba0-0040cee2  4247266          Walls   

      family_names                  type_names host_ids   BB_X_dims  \
897     Basic Wall                     בלוק 10        -  278.500000   
1267    Basic Wall                     בטון 15        -   40.000000   
8598         Floor  פנים 25 + 15 - ריצוף 60/60        -   40.000000   
18027   Basic Wall           Generic - 350mm 2        -  630.000000   
16722   Basic Wall                 BO-INT Bl15        -  285.051868   

       BB_Y_dims   BB_Z_dims  BB_volumes  \
897        285.5   10.000000    795117.5   
1267       215.0   15.000000    129000.0   
8598       260.0  129.871986   1350000.0   
18027     2870.0   35.000000  63300000.0   
16722      305.0   15.000000   1300000.0   

                                 BB_centers BB_plane_Zs  solid_volumes  \
897     {7099.118821, 4182.128799, 2502.75}    {0,-1,0}       613342.5   
1267     {5917.667802, 4761.650604, 3157.5}     {1,0,0}       129000.0   
8598   {-15403.160085, 8541.148375, 1245.0}     {0,1,0}      1300000.0   
18027      {-1525.040111, -1102.930017, 35}     {0,1,0}     62900000.0   
16722   {4240.300753, 1832.801264, 2417.62}     {0,1,0}      1300000.0   

      room_names  
897            -  
1267           -  
8598           -  
18027          -  
16722          -

Organize Dataset by Name


In [3]:
dataset=ds[["category_names","BB_X_dims","BB_Y_dims","BB_Z_dims","BB_volumes","solid_volumes"]]
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values
print(X)
# sampleArray=np.array(X)
# convertedArray = sampleArray.astype(np.float)


[[2.78500000e+02 2.85500000e+02 1.00000000e+01 7.95117500e+05
  6.13342500e+05]
 [4.00000000e+01 2.15000000e+02 1.50000000e+01 1.29000000e+05
  1.29000000e+05]
 [4.00000000e+01 2.60000000e+02 1.29871986e+02 1.35000000e+06
  1.30000000e+06]
 ...
 [2.80000000e+02 1.94987535e+02 1.00000000e+01 5.45965098e+05
  5.45965098e+05]
 [1.95576866e+02 2.70000000e+02 1.40000000e+01 7.39280554e+05
  5.04080555e+05]
 [1.10000000e+02 2.00000000e+02 2.86501670e+01 6.30303663e+05
  2.25451521e+05]]


Encoing the Independent Var

In [4]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

Encoding Dependent Var


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Splitting Dataset into training set and test set


In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
print(X_train)

[[2.94952478e+02 2.75500000e+02 2.00000000e+01 1.63000000e+06
  1.63000000e+06]
 [3.10000000e+02 5.62947910e+02 2.00000000e+01 3.49000000e+06
  3.49000000e+06]
 [9.65000000e+01 2.21000000e+02 4.00000000e+01 8.53060000e+05
  1.08367442e+05]
 ...
 [8.20000000e+01 2.15500000e+02 2.90000000e+01 5.12459000e+05
  1.14632114e+05]
 [9.00000000e+01 8.12800000e+01 7.50000000e+01 5.48640000e+05
  2.87343644e+05]
 [8.50000000e+01 2.40000000e+02 2.00000000e+01 4.08000000e+05
  4.08000000e+05]]


In [8]:
print(X_test)

[[1.84988335e+02 6.54697470e+01 7.50121600e+01 9.08482737e+05
  2.59865007e+05]
 [4.10000000e+01 7.17010190e+01 3.96000000e+02 1.16000000e+06
  1.16000000e+06]
 [3.30000000e+02 4.99739780e+01 2.00000000e+01 3.29828255e+05
  3.29828255e+05]
 ...
 [2.00000000e+02 1.21296026e+02 3.98475000e+01 9.66668679e+05
  3.97432435e+04]
 [8.50000000e+01 1.00000000e+00 8.00000000e+01 6.80000000e+03
  6.80000000e+03]
 [5.00000000e+01 6.14113052e+02 1.03799945e+03 3.19000000e+07
  2.01000000e+07]]


In [9]:
print(y_train)

[4 4 0 ... 0 2 4]


In [10]:
print(y_test)

[3 1 4 ... 5 3 1]


Feature Scalling


In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Trainig the SVM Model on the training set


In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

Confusion Matrix


In [13]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  15    0   23    0  435    0]
 [   1  218   47    4   11    0]
 [   0   27  304    0   21    0]
 [  13    2  253    2   20    0]
 [   1    0   12    0 1962    0]
 [   2    7  120    0  260    0]]


0.6651595744680852