

> Import Libraries




In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import Data and Shuffle

In [2]:
data_set_merge=pd.read_csv("dataset-02-clean.csv")

ds =data_set_merge.sample(frac=1)
ds.head()

unique_ids       ids  \
16777  f09cd8d9-7c51-45f8-8029-4a9be38b8ff8-0040e68a   4253322   
7244   7a16c7d4-23a9-40d8-93a8-1606d3a5ed5b-008494de   8688862   
8843   aaf9c9de-3535-4b84-8521-061864cfdf99-00e370e4  14905572   
12360  6de6eb6a-bcbf-4e08-a866-d954b83f7159-000acb47    707399   
11559  1135d666-8bb8-460c-bdcf-fae791167678-010aca86  17484422   

          category_names     family_names               type_names host_ids  \
16777              Walls       Basic Wall               BO-INT Bl5        -   
7244               Walls       Basic Wall  קיר בלוק 15+ טיח פנים 2        -   
8843               Walls       Basic Wall   00 - EXT-MMD-Conc-20cm        -   
12360              Walls       Basic Wall             BO-INT Con50        -   
11559  Plumbing Fixtures  V1_קולטן+צמג+צא                 "4 קולטן        -   

        BB_X_dims    BB_Y_dims  BB_Z_dims  BB_volumes  \
16777   20.000000   310.000000        5.0     31000.0   
7244    87.300000   120.000000       17.0    178092.0   
8843   330.000000   249.999214       20.0   1650000.0   
12360  235.009133   260.000000       25.0   1530000.0   
11559   10.400000  2800.000000       10.4    302848.0   

                                BB_centers BB_plane_Zs  solid_volumes  \
16777  {5235.253341, 1202.301326, 1095.12}     {1,0,0}   3.100000e+04   
7244    {-3339.02262, -755.665918, 2795.0}     {1,0,0}   1.780920e+05   
8843    {1043.481992, 1444.680584, 1155.0}     {0,1,0}   1.310000e+06   
12360    {5045.27003, 2197.801264, 150.12}     {0,1,0}   1.530000e+06   
11559    {-514.543904, 697.012106, 1400.0}     {0,1,0}   2.378566e+05   

      room_names  
16777          -  
7244           -  
8843           -  
12360          -  
11559          -

Organize Dataset by Name


In [99]:
dataset=ds[["category_names","BB_X_dims","BB_Y_dims","BB_Z_dims","BB_volumes","solid_volumes"]]
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values
print(X)
# sampleArray=np.array(X)
# convertedArray = sampleArray.astype(np.float)


[[2.42056893e+02 1.85000000e+02 2.00000000e+01 8.95610505e+05
  8.95610505e+05]
 [8.00000000e+01 9.07872940e+01 5.61584060e+01 4.07877580e+05
  4.78992079e+04]
 [4.84504130e+01 7.34950730e+01 5.53910150e+01 1.97240016e+05
  7.77619122e+03]
 ...
 [3.00000000e-01 6.00000000e+01 1.15000000e+02 2.07000001e+03
  2.07000000e+03]
 [2.50000000e+02 5.00000000e+01 1.90000000e+02 2.38000000e+06
  8.42857861e+05]
 [8.46419890e+01 1.20000000e+02 2.00000000e+00 2.03140773e+04
  2.03140773e+04]]


Encoing the Independent Var

In [94]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# X = np.array(ct.fit_transform(X))

Encoding Dependent Var


In [100]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

Splitting Dataset into training set and test set


In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [102]:
print(X_train)

[[1.88000000e+02 2.51000000e+02 2.98432150e+01 1.41000000e+06
  1.06096252e+05]
 [2.00000000e+02 1.21296026e+02 4.48475000e+01 1.09000000e+06
  4.00898328e+04]
 [5.60396070e+01 3.42500000e+02 2.50000000e+01 4.79839131e+05
  4.65221520e+05]
 ...
 [7.00000000e+01 2.10000000e+02 1.40000000e+01 2.05800000e+05
  9.51000000e+04]
 [9.00000000e+01 3.05000000e+02 1.00000000e+01 2.74500000e+05
  2.74500000e+05]
 [1.70000000e+01 4.95928704e+02 2.04996132e+02 1.73000000e+06
  1.73000000e+06]]


In [103]:
print(X_test)

[[3.04800000e+01 1.82880000e+02 1.21920000e+02 6.79604318e+05
  1.89322800e+05]
 [4.16000000e+00 2.59500000e+00 1.52000000e-01 1.64087000e+00
  1.64087000e+00]
 [1.00000000e+01 2.10000000e+02 1.34799787e+03 2.83000000e+06
  3.45599573e+05]
 ...
 [8.12800000e+01 9.00000000e+01 7.00000000e+01 5.12064000e+05
  2.70608641e+05]
 [7.00000000e+01 2.10000000e+02 7.40000000e+00 1.08780000e+05
  7.92600000e+04]
 [3.42268676e+02 2.80000000e+02 2.00000000e+01 1.92000000e+06
  1.92000000e+06]]


In [104]:
print(y_train)

[5 5 4 ... 0 4 1]


In [105]:
print(y_test)

[2 4 1 ... 2 0 4]


Feature Scalling


In [106]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Trainig the SVM Model on the training set


In [107]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)

SVC(kernel='linear', random_state=0)

Confusion Matrix


In [109]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  19    0   19    1  433    0]
 [   3  233   34    5   12    0]
 [   0   25  296    0   32    0]
 [  14    3  241    2   27    0]
 [   3    1   10    0 1960    0]
 [   1    5  102    0  277    2]]


0.6680851063829787